# Generated by Django 3.2.7 on 2021-10-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_bio_userpersonalizado_biografia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpersonalizado',
            old_name='Biografia',
            new_name='biografia',
        ),
        migrations.AlterField(
            model_name='userpersonalizado',
            name='foto_perfil',
            field=models.ImageField(blank=True, upload_to='fotos_perfil', verbose_name='Foto de Perfil'),
        ),
    ]
