# Generated by Django 3.2.7 on 2021-10-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='categoria_especial',
            field=models.CharField(choices=[('0', 'Não definido'), ('1', 'Amigos'), ('2', 'Família')], default='0', max_length=1),
        ),
        migrations.DeleteModel(
            name='CategoriaEspecial',
        ),
    ]
